# Generated by Django 4.2.2 on 2023-06-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='example@example.com', max_length=100),
        ),
    ]
