# Generated by Django 4.2.2 on 2023-06-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pasajero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='reservo_transfer',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='chofer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
